<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://localhost:8001/viviendaService"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             targetNamespace="http://localhost:8001/viviendaService">

    <message name="ObtenerViviendaRequest">
        <part name="id" type="xsd:int"/>
    </message>

    <message name="ObtenerViviendaResponse">
        <part name="id_vivienda" type="xsd:int"/>
        <part name="barrio" type="xsd:string"/>
        <part name="manzana" type="xsd:string"/>
        <part name="lote" type="xsd:string"/>
        <part name="numeroExpediente" type="xsd:string"/>
        <part name="mensaje" type="xsd:string"/>
    </message>

    <portType name="ViviendaPortType">
        <operation name="ObtenerVivienda">
            <input message="tns:ObtenerViviendaRequest"/>
            <output message="tns:ObtenerViviendaResponse"/>
        </operation>
    </portType>




    <binding name="ViviendaBinding" type="tns:ViviendaPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="ObtenerVivienda">
            <soap:operation soapAction="ObtenerVivienda"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>

    <service name="ViviendaService">
        <documentation>Servicio para obtener información de una vivienda</documentation>
        <port name="ViviendaPort" binding="tns:ViviendaBinding">
            <soap:address location="http://localhost:8001/viviendaService"/>
        </port>
    </service>
</definitions>
